WITH races AS (SELECT unnest(ARRAY['FL-10-general','FL-11-general','FL-12-general','FL-14-general','FL-15-general','FL-16-general','FL-20-general','FL-22-general','FL-24-general','FL-25-general','FL-26-general','FL-27-general','FL-28-general','FL-7-general','FL-8-general','FL-9-general','FL-AGR-general','FL-ATG-general','FL-BRO-SB1-general','FL-BRO-SB4-general','FL-BRO-SB7-general','FL-DAD-CC2-general','FL-DAD-CC5-general','FL-DAD-SB1-general','FL-HIL-CC1-general','FL-HIL-CC3-general','FL-HIL-CC5-general','FL-HIL-CC7-general','FL-HIL-SB2-general','FL-ORA-CC2-general','FL-ORA-CC7-general','FL-ORA-CC8-general','FL-ORA-MAYOR-general','FL-ORA-SB2-general','FL-SEN-general']::text[]) AS race_id)
SELECT r.race_id,
 (SELECT count(*) FROM claim WHERE race_id=r.race_id)::int AS n_claims,
 (SELECT md5(coalesce(string_agg(claim_id||'|'||candidate_id||'|'||issue_id||'|'||text||'|'||bucket||'|'||attributed::text||'|'||coalesce(verification,'')||'|'||coalesce(verdict,''), E'\n' ORDER BY claim_id COLLATE "C"),'')) FROM claim WHERE race_id=r.race_id) AS claims,
 (SELECT md5(coalesce(string_agg(cs.claim_id||'|'||s.url_norm||'|'||s.url||'|'||s.type, E'\n' ORDER BY cs.claim_id COLLATE "C", s.url_norm COLLATE "C"),'')) FROM claim_source cs JOIN claim c USING (claim_id) JOIN source s USING (source_id) WHERE c.race_id=r.race_id) AS claim_sources,
 (SELECT md5(coalesce(string_agg(position_id||'|'||candidate_id||'|'||issue_id||'|'||array_to_string(claim_ids,',')||'|'||attributed::text||'|'||coverage||'|'||stance_summary, E'\n' ORDER BY position_id COLLATE "C"),'')) FROM position WHERE race_id=r.race_id) AS positions,
 (SELECT md5(coalesce(string_agg(issue_id||'|'||tier||'|'||coalesce(candidate_id,'')||'|'||title||'|'||display_order::text, E'\n' ORDER BY issue_id COLLATE "C"),'')) FROM issue WHERE race_id=r.race_id) AS issues,
 (SELECT md5(coalesce(string_agg(candidate_id||'|'||array_to_string(facts,',')||'|'||array_to_string(positions,',')||'|'||array_to_string(opinions,',')||'|'||(audit - 'balance_check_passed' - 'flag_reason' - 'flagged_at')::text, E'\n' ORDER BY candidate_id COLLATE "C"),'')) FROM profile WHERE race_id=r.race_id) AS profiles
FROM races r ORDER BY r.race_id COLLATE "C";
