-- Generated by scripts/build-election-seed.mjs — do not edit by hand.
-- Statewide FL 2026 election dates from https://dos.fl.gov/elections/for-voters/election-dates/
-- (fetched 2026-07-06). verified_by is NULL by design: founder task F4
-- verifies each row against the source before anything can send.
-- Idempotent: ON CONFLICT DO NOTHING against uq_election_event_scope.

INSERT INTO election_event (event_type, election, event_date, details_url) VALUES
  ('registration_deadline', 'primary_2026', '2026-07-20', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('vbm_request_deadline', 'primary_2026', '2026-08-06', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('early_voting_start', 'primary_2026', '2026-08-08', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('early_voting_end', 'primary_2026', '2026-08-15', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('election_day', 'primary_2026', '2026-08-18', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('registration_deadline', 'general_2026', '2026-10-05', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('vbm_request_deadline', 'general_2026', '2026-10-22', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('early_voting_start', 'general_2026', '2026-10-24', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('early_voting_end', 'general_2026', '2026-10-31', 'https://dos.fl.gov/elections/for-voters/election-dates/'),
  ('election_day', 'general_2026', '2026-11-03', 'https://dos.fl.gov/elections/for-voters/election-dates/')
ON CONFLICT DO NOTHING;
