-- Census block -> congressional district, for address lookup (spec
-- docs/superpowers/specs/2026-09-09-address-district-lookup-design.md).
--
-- Ranges, not one row per block: districts cluster by tract, so run-length
-- encoding the sorted 15-digit GEOIDs turns the four covered counties' 89,816
-- blocks into 982 rows. GEOIDs are fixed width, so a lexicographic BETWEEN is
-- numerically correct.
--
-- Seeded by 0026_block_seed_2026.sql, generated by scripts/build-block-seed.mjs
-- from the same enacted-plan file 0022_zip_seed_2026.sql's crosswalk is built
-- from -- which is what stops an address and a ZIP disagreeing about a district.
CREATE TABLE block_district (
  block_start            CHAR(15) PRIMARY KEY,
  block_end              CHAR(15) NOT NULL,
  county_fips            CHAR(5)  NOT NULL,
  congressional_district TEXT     NOT NULL,
  CONSTRAINT block_district_range_ordered CHECK (block_end >= block_start)
);

-- The lookup is always "which range contains this GEOID".
CREATE INDEX idx_block_district_range ON block_district (block_start, block_end);
