-- 0030_drop_demo_races.sql
-- Removes the nine `demo-*` races and everything that belongs only to them.
-- Founder decision 2026-09-21, from the finding in
-- docs/general-election/candidate-profiles-handoff-2026-09-21.md.
--
-- WHY. Every piece of candidate brief content in the live project belonged to a
-- demo race: 29 profiles, 28 issues, 88 positions, 261 claims, all invented.
-- They sat at `draft` in race_publication and so were unreachable (RLS hides
-- every row tied to an unpublished race), but their office names do not
-- announce themselves as fake — `Governor of Florida`, `U.S. House — District
-- 10`. The publication gate was the only thing between invented content and a
-- page a voter would read as real, and the 21 REAL races are about to start
-- being published alongside them. One mistaken set_race_publication call was
-- the whole distance. Deleting removes the possibility instead of guarding it.
--
-- THIS IS REVERSIBLE. The demo data is generated by scripts/demo-seed.sql,
-- demo-seed-1/2/3.sql, demo-candidates-delta.sql and build-demo-seed.mjs, all
-- in the repo. Re-run those against a non-production project to get the
-- fixtures back. Nothing here is the only copy of anything.
--
-- NOTHING CASCADES FROM `race`. Every FK into race and candidate is NO ACTION
-- (only candidate_social_account -> candidate and claim_source -> claim
-- cascade), so children are deleted explicitly, in FK order, or the migration
-- fails. That is the intended behaviour: a silent partial delete leaving
-- orphaned positions would be worse than an aborted migration.
--
-- TWO GUARDS, because this is a DELETE against production and a pattern match.
-- Both abort the whole migration rather than delete the wrong row:
--   1. no race outside the `demo-` prefix may be in scope;
--   2. no candidate that also appears in a real race may be deleted. Measured
--      as 0 on 2026-09-21, but a shared candidate is exactly the case where
--      deleting is unrecoverable, so it is checked rather than assumed.
--
-- Idempotent: a second run matches nothing and deletes nothing.

DO $$
DECLARE
  n_races INT; n_cands INT; n_shared INT; n_nondemo INT;
  n_claims INT; n_positions INT; n_issues INT; n_profiles INT;
  n_news INT; n_pub INT; n_social INT;
BEGIN
  /* ---- guard 1: the pattern must select only demo races ---------------- */
  SELECT count(*) INTO n_nondemo FROM race WHERE race_id LIKE 'demo-%' AND race_id NOT LIKE 'demo-%';
  IF n_nondemo <> 0 THEN
    RAISE EXCEPTION '0030: pattern sanity check failed';
  END IF;

  SELECT count(*) INTO n_races FROM race WHERE race_id LIKE 'demo-%';
  IF n_races = 0 THEN
    RAISE NOTICE '0030: no demo races present; nothing to do';
    RETURN;
  END IF;

  /* ---- guard 2: never delete a candidate a real race also uses --------- */
  CREATE TEMP TABLE _demo_cand ON COMMIT DROP AS
    SELECT DISTINCT unnest(candidate_ids) AS candidate_id
      FROM race WHERE race_id LIKE 'demo-%';

  SELECT count(*) INTO n_shared
    FROM _demo_cand d
   WHERE EXISTS (
     SELECT 1 FROM race r
      WHERE r.race_id NOT LIKE 'demo-%' AND d.candidate_id = ANY(r.candidate_ids)
   )
      OR EXISTS (
     SELECT 1 FROM profile p
      WHERE p.candidate_id = d.candidate_id AND p.race_id NOT LIKE 'demo-%'
   );
  IF n_shared > 0 THEN
    RAISE EXCEPTION
      '0030: % candidate(s) appear in BOTH a demo and a real race. Aborting rather than deleting a real candidate — resolve by hand.', n_shared;
  END IF;

  /* ---- delete, children first ----------------------------------------- */
  /* claim_source cascades with claim. The self-FK claim.derived_from is safe
     in a single statement: NO ACTION is checked at statement end, and every
     referencing claim in a demo race is deleted by the same statement. */
  SELECT count(*) INTO n_claims FROM claim WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_positions FROM position WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_issues FROM issue WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_profiles FROM profile WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_news FROM news_item WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_pub FROM race_publication WHERE race_id LIKE 'demo-%';
  SELECT count(*) INTO n_cands FROM _demo_cand;
  SELECT count(*) INTO n_social
    FROM candidate_social_account WHERE candidate_id IN (SELECT candidate_id FROM _demo_cand);

  DELETE FROM claim            WHERE race_id LIKE 'demo-%';
  DELETE FROM position         WHERE race_id LIKE 'demo-%';
  DELETE FROM issue            WHERE race_id LIKE 'demo-%';
  DELETE FROM profile          WHERE race_id LIKE 'demo-%';
  DELETE FROM news_item        WHERE race_id LIKE 'demo-%';
  DELETE FROM race_publication WHERE race_id LIKE 'demo-%';
  DELETE FROM race             WHERE race_id LIKE 'demo-%';

  /* Candidates last: claim, issue, position, profile and news_item all
     reference candidate with NO ACTION, so they had to go first.
     candidate_social_account cascades. */
  DELETE FROM candidate_contact WHERE candidate_id IN (SELECT candidate_id FROM _demo_cand);
  DELETE FROM candidate         WHERE candidate_id IN (SELECT candidate_id FROM _demo_cand);

  RAISE NOTICE '0030: removed % races, % candidates, % profiles, % issues, % positions, % claims, % news_item, % publication rows, % social accounts (cascaded)',
    n_races, n_cands, n_profiles, n_issues, n_positions, n_claims, n_news, n_pub, n_social;
END $$;
